name: Mohammed-Imran
on: [issues, workflow_dispatch, fork]
jobs:
  first_job:
    runs-on: macos-latest
    steps:
      - name: Get_code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependency
        run: echo "Dependency has been installed"
      - name: Run test
        run: echo " Test completed with out any errors"
  deploy:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
        - name: get Code
          uses: actions/checkout@v3
        - name: Install Node-JS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependency
          run: echo " Dependency Installed "
        - name: Build Project
          run: echo "Building the project "
        - name: Deploy
          run: echo "Deploying....."
    
